In [4]:
#First , import Numpy

import numpy as np

from Health_Project.env.Lib.calendar import weekday
from Health_Project.env.Lib.tarfile import data_filter

## DataTpes and Attributes for Numpy


ModuleNotFoundError: No module named 'Health_Project'

## DataTpes and Attriutes for Numpy

In [5]:
#NumPy  main dataype is Ndarray

myj = np.array([1,2,3,4,5])
myj

array([1, 2, 3, 4, 5])

In [ ]:
type(myj)

In [6]:
myj2 = np.array([[1,2.0,3.0],[4,5,6.5]])

myj3 = np.array( [[ [1,2,3] ,
                    [4,5,6],
                    [7,8,9]],
                    [[10,11,12],
                     [13,14,15],
                     [15,16,17] ]] )


In [7]:
#Array Shape :
myj2.shape

(2, 3)

In [8]:
myj2.shape

(2, 3)

In [11]:
myj3.shape

(2, 3, 3)

In [12]:
myj.ndim,myj2.ndim,myj3.ndim

(1, 2, 3)

In [13]:
myj.dtype , myj2.dtype , myj3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
myj.size , myj2.size , myj3.size


(5, 6, 18)

In [15]:
type(myj),type(myj2),type(myj3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [9]:
##Creating a datafrome for a Numpy array

import pandas as pd
df = pd.DataFrame(myj2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

##Creating NumpyArrays

In [10]:
sami = np.array([1,2,3,4,5,6,7,8,9,10])
sami

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
sami.dtype

dtype('int64')

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [ ]:
type(ones)

In [14]:
zeros = np.zeros((2,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0,10,2) # Start step stop
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10 , size =(3,5)) # Array contain 0 as the low value and 10 as a high value.
random_array

array([[9, 3, 4, 3, 1],
       [4, 4, 5, 6, 6],
       [5, 5, 2, 0, 1]], dtype=int32)

In [ ]:
random_array.size


In [ ]:
random_array.shape

In [ ]:
random_array2 = np.random.randn(5,3) # 5 rows 3 column

In [ ]:
random_array2

In [ ]:
random_array2.shape

In [ ]:
random_array3 = np.random.rand(5,3)
random_array3

In [ ]:
# Pseudo - Randmon Numbers
#me = np.random.seed() == Use seed for random numberts that are reproducable.
np.random.seed(0)
random_array4 = np.random.randint(10, size = (5,3))
random_array4


In [ ]:
np.random.seed(7) # Code for using a specific seed for randomizing numbers. It locks it.
random_array5 = np.random.randint(10, size = (5,3))
random_array5

In [ ]:
random_array5.shape


In [ ]:
np.random.seed(5)
random_array5 = np.random.random ((5,3))
random_array5

In [ ]:
random_array5 = np.random.random((5,3))
random_array5

## Viewing arrays and Matrices

In [ ]:
random_array6 = np.unique(random_array5)
random_array6

In [ ]:
a1

In [ ]:
a4 = np.random.randint(10, size = (2,3,4,5)) # Try to understand this
a4

In [ ]:
# Get the first 4 numbers of the inner most array

a4[:,:,:,0:1]

##Manipulating and COmpares Arrays

In [ ]:
#Arithmetic
zeros


In [ ]:
ones

In [ ]:
a1 = np.array([1,2,3,])
a1
a1

In [ ]:
a2 = np.array([[1.0,2.0,3.3],[4.0,5.0,6.5]])
a2

In [ ]:
a1*a2

In [ ]:
random_array3

In [ ]:
a3 = np.array( [[ [1,2,3] ,
                    [4,5,6],
                    [7,8,9]],
                    [[10,11,12],
                     [13,14,15],
                     [15,16,17] ]] )

In [ ]:
a3

In [ ]:
a2*a3

In [ ]:
#How to reshape a2 ro be compitabile woth a3
#Search : How to reshape numpy array

a1 / ones


In [ ]:
#Floor --  Removing the decimals
a2 // a1

In [ ]:
a2**2

In [ ]:
np.square(a2)

In [ ]:
np.add(a2,a1)

In [ ]:
np.add(a1,a2)

In [ ]:
a1 % 2

In [ ]:
a2 % 2


## Aggregation
Aggregation is the performing the same operations on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)


In [ ]:
sum(listy_list)


In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

#Use python method (sum()) on python datatypes and use
#Numpy methods (np.sum())on Numpy Arrays


In [ ]:
#Creation a massive Numpy Array
massive_array = np.random.random ( (100000) )
massive_array.size

In [ ]:
massive_array.shape

In [ ]:
massive_array[:10] # Slice array for 10 values

In [ ]:
%timeit sum(massive_array) # Python sume
%timeit np.sum(massive_array) # Numpy sum


In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.median(a2)
np.max(a2)
#Standard deviatio is the squaroot of the variance
np.std(a2)


In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher Variance =  Wider range of the numbers
# Lower variance  =  lower range of numbers
np.var(a2)


In [ ]:
#Standard deviation =  Square root of t variance

np.sqrt(np.var(a2))

In [ ]:
#Demo of std and VAr
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])
#finding the variance
np.var(high_var_array),np.var(low_var_array)

In [ ]:
np.std(high_var_array),np.std(low_var_array) # Standard deviation

In [ ]:
np.mean(high_var_array),np.mean(low_var_array) # Mean

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)

### Reshaping and Transposing

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2

In [ ]:
a2 * a3

In [ ]:
#Reshaping the array
a2.reshape()

In [ ]:
a2.reshape(2,3,1)

In [ ]:
a2_reshape = a2.reshape (2,3,1)
a2_reshape


In [ ]:
a2 * a3

In [ ]:
a3 * a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3.T.shape

## DOT Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

mat1


In [ ]:
mat2

In [ ]:
mat1.shape

In [ ]:
mat2.shape

In [ ]:
mat1*mat2

In [ ]:
mat1 * mat2  # Element-wise multiplication

In [ ]:
# Dot Product
np.dot(mat1,mat2)

In [ ]:
#Transpose Mat1
mat1.T


In [ ]:
mat1.T.shape


In [ ]:
mat1.shape

In [ ]:
mat2.T.shape

In [ ]:
mat3 = np.dot(mat1,mat2.T)

In [ ]:
mat3

In [ ]:
mat3.shape

## Dot product Example ( Nut Butter Sales )

In [ ]:
np.random.seed(0)
#Number of Jars Sold
sales_amount = np.random.randint(20, size = (5,3))

In [ ]:
sales_amount

In [ ]:
#CReate Prices_Array

prices = np.array([10,8,12])
prices

In [ ]:
# price dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ['Price'],
                    columns =['Almond Butter','Peanut Butter','Cashew Butter'])
butter_prices


In [ ]:
total_sales = prices.dot(sales_amount.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape , weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales

In [ ]:
#Transpose daily sales to chane the size and add it to weekly sales

#daily_sales =daily_sales.T.shape
daily_sales



In [ ]:
weekly_sales['Total'] = daily_sales.T
weekly_sales

In [ ]:
#Try it on your own

## Dot Product ( Car Sales )

In [ ]:
np.random.seed(0)
#Number of Cars Sold
csales_amount = np.random.randint(20, size = (6,4))
csales_amount

In [ ]:
#Create an amount
prices = np.array([55000,25000,33000,42000])
prices

In [ ]:
csales_prices = pd.DataFrame(prices.reshape(1,4), index = ["Price"],
                                columns = ['BMW','Toyota','Honda','Jaguar'])
csales_prices

In [ ]:
# Mapping days of the week to sales
weekly= pd.DataFrame(csales_amount, index =['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
          columns = ['BMW','Toyota','Honda','Jaguar'])
weekly
#csales_prices.shape , weekly.shape


In [ ]:
#Daily Sales
daily_csales = csales_prices.dot(weekly.T)
daily_csales


In [ ]:
# Total Sales
weekly['Total Sale'] = daily_csales.T
weekly


### Comparison Operators - Logic FUnctions

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
a1 >= a2

In [ ]:
bool_array = a1 > a2
bool_array.dtype ,

In [ ]:
a1 == a1


In [ ]:
a1 == a2

## SOrting Arrays

In [ ]:
random_array = np.random.randint(10,size =(3,5))
random_array

In [ ]:
random_array.shape

In [ ]:
#Sorting
np.sort(random_array)

In [ ]:
random_array
np.argsort(random_array)

## Practical Example of Numpy In Actions


<img src="./images/panda.png" />

In [ ]:
#Turn Image into Numpy Array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

In [236]:
panda.size, panda.shape, panda.ndim


(24465000, (2330, 3500, 3), 3)

In [237]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="./images/car-photo.png" />

In [1]:
car = imread("images/car-photo.png")
print(type(car))

NameError: name 'imread' is not defined

In [238]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

HTML

<img src="./images/dog-photo.png" />

In [241]:
dog = imread("images/dog-photo.png")
print(type(dog))


<class 'numpy.ndarray'>


In [242]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)