# My Pandas Practice Zero to master  - by Millinkan @ 03-2025

I created this notebook to test my knowledge in practicing different tasks with Numpy.

For further reference and resources, I used the main documentation from the library creators [NumPy documentation](https://numpy.org/devdocs/user/index.html) ,the tutorial and Stack Overflow:

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [11]:
# Create a 1-dimensional NumPy array using np.array()
np_array_1d = np.array([1, 2, 3, 4, 5])
#np_array_1d
# Create a 2-dimensional NumPy array using np.array()
np_array_2d = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
#np_array_2d
# Create a 3-dimensional Numpy array using np.array()
np_array_3d = np.array([ [[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]],
                         [[10, 11, 12],
                          [13, 14, 15],
                          [16, 17, 18]],
                         ])
np_array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np_array_1d.shape, np_array_1d.ndim, np_array_1d.dtype, np_array_1d.size

((5,), 1, dtype('int64'), 5)

In [4]:
# Attributes of 2-dimensional array
np_array_2d.shape, np_array_2d.ndim, np_array_2d.dtype, np_array_2d.size

In [5]:
# Attributes of 3-dimensional array
np_array_3d.shape, np_array_3d.ndim, np_array_3d.dtype, np_array_3d.size

In [19]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
np_df = pd.DataFrame(np_array_2d)
np_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [32]:
# Create an array of shape (10, 2) with only ones : The full key word can be used as "np.full()"
#array_ones = np.ones((10, 2))
#array_ones
#Create an array of shape (7, 2) with only fives
array_fives = np.full((7, 2), 5) # array of fives of shape (7, 2)

arrays_zeros= np.full((10, 2),0) # array of zeros of shape (10, 2)
arrays_zeros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [33]:
# Create an array of shape (7, 2, 3) of only zeros
np_array_3d_zeros = np.zeros((7, 2, 3))
np_array_3d_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
# Create an array within a range of 0 and 100 with step 3
np_array_range = np.arange(0, 101, 3) # array of numbers between 0 and 100 with step 3
np_array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [36]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np_array_random = np.random.randint(0, 11, (7, 2)) # array of random numbers between 0 and 10 of size (7, 2)
np_array_random
#Alternative
random_array = np.random.randint(10, size=(7, 2)) # Specify the range and size of the array and  10
random_array

array([[7, 0],
       [8, 6],
       [4, 7],
       [0, 6],
       [3, 3],
       [1, 6],
       [4, 5]], dtype=int32)

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np_array_floats = np.random.rand(3, 5) # array of random floats between 0 and 1 of shape (3, 5)
np_array_floats
# Alternatively
#np_array_floats = np.random.uniform(0, 1, (3, 5)) # introducing a more efficient way to generate random floats
#np_array_floats

array([[0.68682251, 0.18291509, 0.44610702, 0.67703182, 0.64741197],
       [0.15880488, 0.50818112, 0.16601464, 0.78866336, 0.99590979],
       [0.74274201, 0.33017866, 0.52639196, 0.860766  , 0.89229937]])

In [55]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np_array_random_2 = np.random.randint(0, 11, (4, 6)) # array of random numbers between 0 and 10 of size ()
np_array_random_2

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
With the introduction of the random seed, the random number generator starts generating numbers from a specific state,
The numbers are generated in a repeatable manner.

In [61]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np_array_random_3 = np.random.randint(1, 11, (3, 7)) # array of random numbers between 1 and 10 of size ()
np_array_random_3

# Find the unique numbers in the array you just created
#np.unique(np_array_random_3)



array([[10,  2, 10,  4,  8,  7,  9],
       [ 8,  5,  2,  5,  8, 10,  9],
       [ 9,  1,  9,  7,  9,  8,  1]], dtype=int32)

In [62]:
# Find the 0'th index of the latest array you created
np_array_random_3
np_array_random_3[0]


array([10,  2, 10,  4,  8,  7,  9], dtype=int32)

In [63]:
# Get the first 2 rows of latest array you created
np_array_random_3[:2]


array([[10,  2, 10,  4,  8,  7,  9],
       [ 8,  5,  2,  5,  8, 10,  9]], dtype=int32)

In [68]:
# Get the first 2 values of the first 2 rows of the latest array
np_array_random_3[:2, :2]

array([[10,  2],
       [ 8,  5]], dtype=int32)

In [76]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np_array_random_4 = np.random.randint(0, 11, (3, 5)) # array of random numbers between 0 and 10 of size
np_array_random_4
np_array_ones = np.full((3, 5),1) # array of ones of size (3, 5)
np_array_ones


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
# Add the two arrays together

np.add(np_array_random_4, np_array_ones)


array([[ 6,  4, 11, 10,  7],
       [ 9,  7,  1,  1,  9],
       [11,  9,  4,  9,  3]])

In [78]:
# Create another array of ones of shape (5, 3)
np_array_ones_2 = np.ones((5, 3)) # array of ones of size (5, 3)
np_array_ones_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
# Try add the array of ones and the other most recent array together - The shape of the arrays must be compatible for this operation. Product illegal in numpy
# So an error is expected here
np.add(np_array_random_4, np_array_ones_2)


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [80]:
# Create another array of ones of shape (3, 5)
np_array_ones_3 = np.ones((3, 5)) # array of ones of size (3, 5)
np_array_ones_3


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
# Subtract the new array of ones from the other most recent array
np.subtract(np_array_random_4, np_array_ones_3)


array([[ 4.,  2.,  9.,  8.,  5.],
       [ 7.,  5., -1., -1.,  7.],
       [ 9.,  7.,  2.,  7.,  1.]])

In [84]:
# Multiply the ones array with the latest array ##
np.multiply(np_array_random_4, np_array_ones_3)



array([[ 5.,  3., 10.,  9.,  6.],
       [ 8.,  6.,  0.,  0.,  8.],
       [10.,  8.,  3.,  8.,  2.]])

In [85]:
# Take the latest array to the power of 2 using '**'
np.power(np_array_random_4, 2) # Using the inbuilt power operator
#Alternatively
np_array_random_4 ** 2 # Using the inbuilt power operator

array([[ 25,   9, 100,  81,  36],
       [ 64,  36,   0,   0,  64],
       [100,  64,   9,  64,   4]], dtype=int32)

In [86]:
# Do the same thing with np.square()
np.square(np_array_random_4) # Using the inbuilt square function


array([[ 25,   9, 100,  81,  36],
       [ 64,  36,   0,   0,  64],
       [100,  64,   9,  64,   4]], dtype=int32)

In [87]:
# Find the mean of the latest array using np.mean()
np.mean(np_array_random_4) # Using the inbuilt mean function

np.float64(5.733333333333333)

In [88]:
# Find the maximum of the latest array using np.max()
np.max(np_array_random_4) # Using the inbuilt max function

np.int32(10)

In [89]:
# Find the minimum of the latest array using np.min()
np.min(np_array_random_4) # Using the inbuilt min function

np.int32(0)

In [90]:
# Find the standard deviation of the latest array
np.std(np_array_random_4) # Using the inbuilt std function

np.float64(3.2957885584822066)

In [91]:
# Find the variance of the latest array
np.var(np_array_random_4) # Using the inbuilt var function

np.float64(10.86222222222222)

In [92]:
# Reshape the latest array to (3, 5, 1)
np.reshape(np_array_random_4, (3, 5, 1)) # Using the inbuilt reshape function

array([[[ 5],
        [ 3],
        [10],
        [ 9],
        [ 6]],

       [[ 8],
        [ 6],
        [ 0],
        [ 0],
        [ 8]],

       [[10],
        [ 8],
        [ 3],
        [ 8],
        [ 2]]], dtype=int32)

In [95]:
# Transpose the latest array
np.transpose(np_array_random_4) # Using the inbuilt transpose function
#Alternatively
np_array_random_4.T # Using the inbuilt transpose function

array([[ 5,  8, 10],
       [ 3,  6,  8],
       [10,  0,  3],
       [ 9,  0,  8],
       [ 6,  8,  2]], dtype=int32)

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np_array_random_5 = np.random.randint(0, 11, (3, 3)) # array of random numbers between 0 and 10 of size
np_array_random_6 = np.random.randint(0, 11, (3, 2)) # array of random numbers between 0 and 10 of size (3, 2)


In [103]:
# Perform a dot product on the two newest arrays you created. An error is expected here. Arrays must have compatible dimensions for a dot product.
np.dot(np_array_random_5, np_array_random_6)

NameError: name 'np_array_random_5' is not defined

In [104]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np_array_random_7 = np.random.randint(0, 11, (4, 3)) # array of random numbers between 0 and 10 of size
np_array_random_8 = np.random.randint(0, 11, (4, 3)) # array of random numbers between 0 and 10 of size (4, 3)
np_array_random_7


array([[ 0,  7,  6],
       [ 1,  7,  0],
       [10,  8,  8],
       [ 1,  6,  9]], dtype=int32)

In [105]:
# Perform a dot product on the two newest arrays you created
np.dot(np_array_random_7, np_array_random_8) # Using the inbuilt dot function


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?. Transpose one of the arrays before performing the dot product.

In [106]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(np_array_random_7.T, np_array_random_8) # Using the inbuilt dot function with the Transposre function T


array([[ 22,  13,  46],
       [102, 123, 131],
       [ 56, 126, 140]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [108]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np_array_random_9 = np.random.randint(0, 11, (3, 4)) # array of random numbers between 0 and 10 of size
np_array_random_10 = np.random.randint(0, 11, (3, 4)) # array of random numbers between 0 and 10 of size

In [109]:
# Compare the two arrays with '>'
np_array_random_9 > np_array_random_10

array([[False,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`? A table is displayed below with the comparison results with are boolean values.

In [110]:
# Compare the two arrays with '>='
np_array_random_9 >= np_array_random_10

array([[False,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

In [111]:
# Find which elements of the first array are greater than 7
np.where(np_array_random_9 > 7)

(array([0, 0]), array([0, 1]))

In [112]:
# Which parts of each array are equal? (try using '==')
np.where(np_array_random_9 == np_array_random_10)

(array([], dtype=int64), array([], dtype=int64))

In [115]:
# Sort one of the arrays you just created in ascending order
#np_array_random_9
np.sort(np_array_random_9)


array([[2, 2, 8, 8],
       [2, 3, 5, 7],
       [0, 3, 7, 7]], dtype=int32)

In [44]:
# Sort the indexes of one of the arrays you just created
np.argsort(np_array_random_9)

In [116]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(np_array_random_9)

np.int64(0)

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(np_array_random_9)

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(np_array_random_9, axis=1)

array([0, 2, 0])

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(np_array_random_9, axis=0)

In [49]:
# Create an array of normally distributed random numbers
np_array_random_11 = np.random.normal(0, 1, 10000) # array of 10,000 normally distributed random

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np_array_evenly_spaced = np.linspace(1, 100, 10) # array of 10 evenly spaced numbers between 1 and

## Extensions

Checking out this resource is a plus :  [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.
